### ISSUE TITLE
Búsqueda de productos por nombre

### ISSUE THREAD

**Issue by AnaVeronica** [SellAndBuyProject/SellAndBuyWebService#20]

**Comment by ruloCodes** [comment]
Creado servicio y controlador para buscar por nombre

**Comment by AnaVeronica** [comment]
No se puede buscar por palabras que contiene el nombre del producto, sólo el nombre exacto.

**Comment by AnaVeronica** [comment]
No se pueden buscar productos por un nombre compuesto por dos palabras.
